baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '新时代农村奋斗者'
theme = 'ananke'
publishDir = "docs"
canonifyurls = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
